### ISSUE TITLE
リリース作業

### ISSUE THREAD

**Issue by tomari** [arigato-java/JavaButton.crx#1]
グーグルでジャバを通過させた経験のあるトビー先生にリリース作業をお願いしたく

**Comment by tobynet** [comment]
了解いたしました。
一旦リリースができた後、tomariさんに権限を追加しようと思います。

さて、リリースに際しまして、まずは以下を用意して頂きたく思います。

* [ ] **説明文**：  
   参考: ↓ ジャバ人間ブラウザでは 670文字程度。16000文字(!?)まで入れられます。
![2017-03-17_dfbx7](https://cloud.githubusercontent.com/assets/20859/24037463/3c3b6318-0b41-11e7-91f2-2ff0fd26bcf1.png)

　更新情報がある場合は、ここに含めます。

* [ ] **スクショ**: **1280x800 or 640x400  計4枚**
  参考: ピッタリの画像サイズでなくとも、余白を透過にしたPNGであればOKのようです。
　![image](https://cloud.githubusercontent.com/assets/20859/24037562/9c93c4e4-0b41-11e7-9a3a-4ccf4bc39bc6.png)

* (optional) YouTube 動画
* [ ] **アイコン** : 96x96px (128x128px 中に。) ( [参考1] )
* [ ] **カテゴリ** : 以下から選択を。
![2017-03-17_bvktj](https://cloud.githubusercontent.com/assets/20859/24037781/345d68b6-0b42-11e7-820c-fdeb64ab71dc.png)
* [x] **URL** : https://github.com/arigato-java/JavaButton.crx
* [x] **Support**: https://github.com/arigato-java/JavaButton.crx/issues

呪術的なジャバ文章、ジャバリアリスティックな画像加工技術等は、協力可能です。お申し付けください。

[参考1]: https://developer.chrome.com/webstore/images?hl=en-US#iconsize
